#!/usr/bin/env bash
# Check if correct number of arguments provided
if [[ $# -lt 4 ]]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi;

# Assign arguments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Use scp to transfer file to server's home directory
scp -o "StrictHostKeyChecking no" -i "$ssh_key" "$file_path" "$username@$server_ip":~

# Exit with success code
exit 0

