#!/usr/bin/env bash
# Install nginx package
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80 and return "Hello World!" at root
echo "Hello World!" > /var/www/html/index.html
service nginx restart

